### ISSUE TITLE
Colleague review tracking issue (Arash Modaresi Rad)

### ISSUE THREAD

**Issue by mikejohnson51** [mikejohnson51/AHGestimation#1]
@arashmodrad  agreed to provide a domain and code review. Will use this issue to track the review. 

A good starting point is [here](https://joss.readthedocs.io/en/latest/review_checklist.html)

## Process:

1. Please fork the repo
2. Review the following sections: paper, vignettes, and code 
3. For each section please leave a comment in this thread and commit any changes referencing `mikejohnson51/FHGestimation#1` before moving on to the next
5.  When done submit a PR referencing this issue

Thanks for being willing to do it!!

**Comment by arashmodrad** [comment]
Further details and descriptions about the necessity of filtering approaches is needed
