### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by mengqi-z** [mikejohnson51/AHGestimation#12]
Hello @mikejohnson51,

This issue is for the JOSS paper review https://github.com/openjournals/joss-reviews/issues/6145. The comments below mainly address the issues I encountered while following the instructions.

**Installation**

The `AHGestimation` package depends on `DescTools`, which requires R > 4.2.0. I am having trouble installing `AHGestimation` on R 4.1.0 and the installation is fine after I switch to R 4.2.0. Please update the "Installation" instructions and the DESCRIPTION file regarding the required R version.

**Instructions**

I tested the example codes in the [main instruction](https://mikejohnson51.github.io/AHGestimation/index.html). Some example figures are incorrect, which might confuse users. The followings are detailed issues. 

1. The figure under "Fitting single relationships" section has incorrect label of x and y - they should be switched.
2. The middle figure under "Fitting hydraulic systems" is still Q-Y relationship, not Q-TW relationship.
3. I got errors when testing the "Data filtering" example code:
```
filtered_data = nwis %>% 
  select(date, Q = Q_cms, Y = Y_m, V = V_ms, TW = TW_m) %>% 
  # Keep the most recent 10 year
  date_filter(year = 10, keep_max = TRUE) %>% 
  # Keep data within 3 Median absolute deviations (log residuals)
  mad_filter() %>% 
  # Keep data that respects the Q = vA criteria w/in allowance
  qva_filter()
Error in `between()`:
! `left` must be length 1
```

**Paper**

I also tested the examples in the paper. However, I got this error:

```
(data = nwis |> 
   date_filter(10, keep_max = T) |> 
   nls_filter(allowance = 0.5))
Error in `filter()`:
! Problem while computing `..1 = between(df2$Y, (1 - allowance) * df2$pY, (1 + allowance) * df2$pY)`.
Caused by error in `between()`:
! `left` must be length 1
```

I will continue testing once these issues have been resolved. Thank you!

**Comment by mikejohnson51** [comment]
Hi @mengqi-z Thank you so much for diving into this and helping with the process!

- [x] Update R requirements 
- [x] I have made the adjustments to the images mentioned in issue 1 and 2. Thanks!

- [ ] As for the `between()` issues I suspect this is a system issue you might have local. Would you mind sharing the version of `dplyr` you have, and, what the data.frame looks like prior to the failing function?

I suspect this as the tests are all passing related to the filters, and I just added a Github Action to dynamically build the website and vignettes. Each of these are passing at the moment.

**Comment by mabesa** [comment]
Pitching in here as I'm getting an error from the example in the paper as well, but a different one (dplyr Version 1.1.4): 

```
(data = nwis |> date_filter(10, keep_max = TRUE) |> nls_filter(allowance = .5))
Error in `filter()`:
ℹ In argument: `date >= fdate | Q == max(df$Q)`.
Caused by error:
! `..1` must be of size 275 or 1, not size 0.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `filter()`:
ℹ In argument: `date >= fdate | Q == max(df$Q)`.
Caused by error:
! `..1` must be of size 275 or 1, not size 0.
---
Backtrace:
     ▆
  1. ├─AHGestimation::nls_filter(...)
  2. │ └─base::nrow(df)
  3. ├─AHGestimation::date_filter(nwis, 10, keep_max = TRUE)
  4. │ ├─dplyr::filter(df, date >= fdate | Q == max(df$Q))
  5. │ └─dplyr:::filter.data.frame(df, date >= fdate | Q == max(df$Q))
  6. │   └─dplyr:::filter_rows(.data, dots, by)
  7. │     └─dplyr:::filter_eval(...)
  8. │       ├─base::withCallingHandlers(...)
  9. │       └─mask$eval_all_filter(dots, env_filter)
 10. │         └─dplyr (local) eval()
 11. └─dplyr:::dplyr_internal_error(...)
Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.
```

**Comment by mikejohnson51** [comment]
@mabesa Thanks! This was a silly error on my part. When we changed the variable names in the test dataset (#9). I updated all the tests and vignettes but not the paper. Adding a rename call has it working. Thanks!

``` r
library(AHGestimation)

(data = nwis |> 
  dplyr::rename(Q = Q_cms, Y  = Y_m, V= V_ms, TW = TW_m) |>
  date_filter(years = 10, keep_max = TRUE) |> 
  nls_filter(allowance = .5))

#>      siteID       date           Q         Y        V       TW
#> 1  01096500 1987-04-07 317.1486864 3.7651748 1.624584 51.81600
#> 2  01096500 2013-01-17  21.6907048 0.8401875 0.737616 35.05200
#> 3  01096500 2013-04-04  40.2099227 1.1666478 0.975360 35.35680
#> 4  01096500 2013-06-11  55.2178517 1.5349831 1.063752 33.83280
#> 5  01096500 2013-08-19   8.8631731 0.5720217 0.697992 22.25040

```

<sup>Created on 2024-02-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mengqi-z** [comment]
Hi @mikejohnson51,

Thank you for addressing my comments. The `between()` issue got fixed after you added `dplyr::rename(Q = Q_cms, Y = Y_m, V = V_ms, TW = TW_m)` in the example.

I went through all documentations and everything looks good. There are just few more minor comments.

**Paper**

- The Q-TW relationship plot in Figure 1 still need to be updated because it currently shows as Q-Y relationship.
- "Acknowledgements" does not show as a heading in the PDF, possibly due to a formatting issue.

**Other Checks**

- There are two licenses in the packages, and one is not really a license and will show as "Unknown". I believe putting your name in the MIT License is sufficient, and you may not need another empty license.

- Although there is test-coverage in Github workflow and all the tests in `test.R` pass, the test result is not really updated in Codecov. The test-coverage Github Action indicates the repository has been deactivated in Codecov. This should be activated to show the latest automated test coverage in Codecov.

Thank you.

**Comment by mikejohnson51** [comment]
Hi @mengqi-z. Thanks for this feedback! We have made the following changes. Thank you again for your careful attention to this work.

## Paper

- [x] The Q-TW relationship plot in Figure 1 still need to be updated because it currently shows as Q-Y relationship.
"Acknowledgements" does not show as a heading in the PDF, possibly due to a formatting issue.

> I have updated this image to be more informative with better labels. Additionally, the data shown in the TW image has been updated! Thank you for catching this.

## Other Checks

- [x] There are two licenses in the packages, and one is not really a license and will show as "Unknown". I believe putting your name in the MIT License is sufficient, and you may not need another empty license.

> I deleted the LICENSE file that is automatically added with `usethis::use_mit_license()`. It seems fine but will re-add if needed for a reason I certainly do not understand.

- [x] Although there is test-coverage in Github workflow and all the tests in test.R pass, the test result is not really updated in Codecov. The test-coverage Github Action indicates the repository has been deactivated in Codecov. This should be activated to show the latest automated test coverage in Codecov.

> I reactivated the token and this seems to be working. Thank you!

**Comment by mengqi-z** [comment]
Thank you for addressing my comments. Everything looks great! Great work!
