### ISSUE TITLE
Colleague review tracking issue (Jim Coll)

### ISSUE THREAD

**Issue by mikejohnson51** [mikejohnson51/AHGestimation#2]
@JimColl agreed to provide a domain and code review. Will use this issue to track the review. 

A good starting point is [here](https://joss.readthedocs.io/en/latest/review_checklist.html)

## Process:

1. Please fork the repo
2. Review the following sections: paper, vignettes, and code 
3. For each section please leave a comment in this thread and commit any changes referencing `mikejohnson51/FHGestimation#2` before moving on to the next
5.  When done submit a PR referencing this issue

Thanks for being willing to do it!!

**Comment by JimColl** [comment]
See notes in #4

**Comment by mikejohnson51** [comment]
closed with #5
